import React from 'react';
import Card from '../common/Card';
import Button from '../common/Button';
import '../../styles/pages/reports.css';

const ReportViewer = ({ report }) => {
  if (!report) {
    return (
      <Card title="Report Viewer" icon="👁️" padding>
        <div className="report-viewer-empty">
          <div className="empty-icon">📋</div>
          <h3>No Report Generated</h3>
          <p>Generate a report to view it here. You can preview, download, or print the report.</p>
        </div>
      </Card>
    );
  }

  const { 
    title, 
    generatedDate, 
    type, 
    pages, 
    fileSize,
    vehicleInfo,
    taxSummary
  } = report;

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  const getReportTypeLabel = (type) => {
    const types = {
      'summary': 'Summary Report',
      'detailed': 'Detailed Report',
      'dispute': 'Dispute Report',
      'audit': 'Audit Report'
    };
    return types[type] || type;
  };

  return (
    <Card title="Report Viewer" icon="👁️" padding>
      <div className="report-viewer">
        <div className="viewer-header">
          <div className="header-left">
            <h3 className="report-title">{title}</h3>
            <div className="report-meta">
              <span className="meta-item">
                <span className="meta-label">Type:</span>
                <span className="meta-value">{getReportTypeLabel(type)}</span>
              </span>
              <span className="meta-item">
                <span className="meta-label">Generated:</span>
                <span className="meta-value">{formatDate(generatedDate)}</span>
              </span>
              <span className="meta-item">
                <span className="meta-label">Pages:</span>
                <span className="meta-value">{pages}</span>
              </span>
              <span className="meta-item">
                <span className="meta-label">Size:</span>
                <span className="meta-value">{fileSize}</span>
              </span>
            </div>
          </div>
          <div className="header-right">
            <Button variant="outline" icon="🔄">
              Refresh
            </Button>
          </div>
        </div>

        <div className="viewer-preview">
          <div className="preview-placeholder">
            <div className="preview-header">
              <div className="preview-title">
                <h2>{title}</h2>
                <p>Generated by SmartTax System</p>
              </div>
              <div className="preview-logo">ST</div>
            </div>

            <div className="preview-content">
              <div className="preview-section">
                <h3>Vehicle Information</h3>
                <div className="info-grid">
                  <div className="info-item">
                    <span className="info-label">Make/Model:</span>
                    <span className="info-value">{vehicleInfo?.make} {vehicleInfo?.model}</span>
                  </div>
                  <div className="info-item">
                    <span className="info-label">Year:</span>
                    <span className="info-value">{vehicleInfo?.year}</span>
                  </div>
                  <div className="info-item">
                    <span className="info-label">Engine:</span>
                    <span className="info-value">{vehicleInfo?.engineCC}cc</span>
                  </div>
                  <div className="info-item">
                    <span className="info-label">Fuel Type:</span>
                    <span className="info-value">{vehicleInfo?.fuelType}</span>
                  </div>
                </div>
              </div>

              <div className="preview-section">
                <h3>Tax Summary</h3>
                <div className="tax-summary-preview">
                  <div className="summary-row total">
                    <span className="summary-label">Total Tax Payable:</span>
                    <span className="summary-value">KES {taxSummary?.totalTax?.toLocaleString()}</span>
                  </div>
                  <div className="summary-row">
                    <span className="summary-label">Customs Value:</span>
                    <span className="summary-value">KES {taxSummary?.customsValue?.toLocaleString()}</span>
                  </div>
                  <div className="summary-row">
                    <span className="summary-label">CIF Value:</span>
                    <span className="summary-value">KES {taxSummary?.cifValue?.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              <div className="preview-section">
                <h3>Tax Breakdown</h3>
                <div className="breakdown-preview">
                  <div className="breakdown-row">
                    <span className="breakdown-label">Import Duty (35%):</span>
                    <span className="breakdown-value">KES {taxSummary?.importDuty?.toLocaleString()}</span>
                  </div>
                  <div className="breakdown-row">
                    <span className="breakdown-label">Excise Duty:</span>
                    <span className="breakdown-value">KES {taxSummary?.exciseDuty?.toLocaleString()}</span>
                  </div>
                  <div className="breakdown-row">
                    <span className="breakdown-label">VAT (16%):</span>
                    <span className="breakdown-value">KES {taxSummary?.vat?.toLocaleString()}</span>
                  </div>
                  <div className="breakdown-row">
                    <span className="breakdown-label">IDF (2.5%):</span>
                    <span className="breakdown-value">KES {taxSummary?.idf?.toLocaleString()}</span>
                  </div>
                  <div className="breakdown-row">
                    <span className="breakdown-label">RDL (2%):</span>
                    <span className="breakdown-value">KES {taxSummary?.rdl?.toLocaleString()}</span>
                  </div>
                </div>
              </div>
            </div>

            <div className="preview-footer">
              <p>This is a preview of the report. Download the complete report for full details.</p>
              <div className="footer-note">
                <strong>Note:</strong> This report is generated for estimation purposes. Final tax assessment is done by KRA.
              </div>
            </div>
          </div>
        </div>

        <div className="viewer-actions">
          <div className="action-group">
            <h4>Download Options:</h4>
            <div className="download-buttons">
              <Button variant="outline" icon="📄">
                PDF Format
              </Button>
              <Button variant="outline" icon="📊">
                Excel Format
              </Button>
              <Button variant="outline" icon="📋">
                CSV Format
              </Button>
            </div>
          </div>

          <div className="action-group">
            <h4>Other Actions:</h4>
            <div className="other-buttons">
              <Button variant="secondary" icon="🖨️">
                Print Report
              </Button>
              <Button variant="secondary" icon="📧">
                Email Report
              </Button>
              <Button variant="secondary" icon="💾">
                Save to History
              </Button>
              <Button variant="secondary" icon="⚖️">
                Generate Appeal Letter
              </Button>
            </div>
          </div>
        </div>

        <div className="viewer-history">
          <h4>Report History</h4>
          <div className="history-list">
            <div className="history-item">
              <span className="history-name">Previous version (2025-01-14)</span>
              <Button size="small" variant="outline">
                View
              </Button>
            </div>
            <div className="history-item">
              <span className="history-name">Draft version (2025-01-13)</span>
              <Button size="small" variant="outline">
                Restore
              </Button>
            </div>
          </div>
        </div>
      </div>
    </Card>
  );
};

export default ReportViewer;